name: global_iptv_app
description: Global IPTV Streaming Application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
